import type { AppDetail } from "@/types";

// Per-app presentation content, drawn from each app's own landing/site (Aymeric's
// own apps). Keyed by the project slug in projects.ts. FR sourced from the landings,
// EN adapted idiomatically.
export const appDetails: Record<string, AppDetail> = {
  tiboug: {
    oneLiner: {
      fr: "Les fruits & légumes les moins chers du jour, près de chez toi — à La Réunion.",
      en: "The cheapest fruit & veg of the day, near you — in Réunion Island.",
    },
    whatItIs: {
      fr: "App iPhone contre la vie chère à La Réunion : elle affiche les prix réels du jour des fruits & légumes, leur tendance et leur saison, à partir des mercuriales officielles de la DAAF. Un assistant IA compose un panier malin dans ton budget et propose de vraies recettes péi, en français et en kréol.",
      en: "An iPhone app against the high cost of living in Réunion: it shows the real daily prices of fruit & veg, their trend and season, straight from the official DAAF price bulletins. An AI assistant builds a smart basket within your budget and suggests real local recipes, in French and Kréol.",
    },
    keyFeatures: [
      {
        fr: "Prix du jour de chaque fruit/légume, avec tendance (baisse/hausse) et saison",
        en: "Daily price for each fruit/veg, with trend (up/down) and season",
      },
      {
        fr: "Comparaison marchés forains vs grandes surfaces pour le panier le moins cher",
        en: "Open-market vs supermarket comparison to find the cheapest basket",
      },
      {
        fr: "Assistant IA : dis ce que tu veux cuisiner, il compose ton panier dans ton budget",
        en: "AI assistant: say what you want to cook, it builds your basket within budget",
      },
      {
        fr: "Recettes péi générées par l'IA à partir des produits les moins chers et de saison",
        en: "Local recipes generated by AI from the cheapest, in-season produce",
      },
      {
        fr: "Date réelle du relevé toujours affichée — honnêteté sur la fraîcheur des données",
        en: "The real reading date is always shown — honest about data freshness",
      },
    ],
    targetUser: {
      fr: "Les habitants de La Réunion qui veulent manger frais sans se ruiner",
      en: "Réunion residents who want to eat fresh without breaking the bank",
    },
    notable: {
      fr: "S'appuie exclusivement sur les mercuriales officielles open data de la DAAF (licence etalab 2.0), historisées chaque jour pour en extraire la saisonnalité : zéro prix inventé. Stack React Native / Expo + backend Convex.",
      en: "Built exclusively on the DAAF's official open-data price bulletins (etalab 2.0 licence), historised daily to extract seasonality: zero invented prices. React Native / Expo + Convex backend.",
    },
  },
  voicejournal: {
    oneLiner: {
      fr: "Transforme ta voix en journal intime : parle, l'IA transcrit, analyse tes émotions et rédige.",
      en: "Turn your voice into a journal: speak, and AI transcribes, reads your emotions and writes it.",
    },
    whatItIs: {
      fr: "App iOS de journal vocal augmentée par l'IA. Tu parles librement 30 s à 3 min, l'IA transcrit, détecte tes émotions et rédige ton journal à la première personne. Chaque jour, un Mind Score (0-100) reflète ton état émotionnel et se suit dans le temps.",
      en: "An AI-augmented voice-journaling iOS app. Speak freely for 30 s to 3 min; the AI transcribes, detects your emotions and writes your journal in the first person. Each day a Mind Score (0-100) reflects your emotional state and can be tracked over time.",
    },
    keyFeatures: [
      {
        fr: "Enregistrement vocal via une orbe animée minimaliste — parle naturellement",
        en: "Voice capture through a minimalist animated orb — just speak naturally",
      },
      {
        fr: "Mind Score quotidien de 0 à 100 reflétant ton état émotionnel",
        en: "Daily Mind Score from 0 to 100 reflecting your emotional state",
      },
      {
        fr: "Journal rédigé par l'IA à la première personne",
        en: "Journal written by the AI in the first person",
      },
      {
        fr: "Analyse et détection des émotions à partir de ta voix",
        en: "Emotion analysis and detection straight from your voice",
      },
      {
        fr: "Dashboard de stats et tendances (heatmap, distribution, évolution)",
        en: "Stats and trends dashboard (heatmap, distribution, evolution)",
      },
    ],
    targetUser: {
      fr: "Toute personne qui veut tenir un journal et suivre son bien-être émotionnel en parlant",
      en: "Anyone who wants to journal and track their emotional well-being just by talking",
    },
    notable: {
      fr: "Angle « journal vocal + IA » : la voix devient la seule interface d'écriture, l'IA analyse et reformule, avec un Mind Score quotidien comme métrique de suivi. App iOS native, essai gratuit.",
      en: "A “voice + AI journal” angle: voice becomes the only writing interface, the AI analyses and rewrites, with a daily Mind Score as the tracking metric. Native iOS app, free trial.",
    },
  },
  tookta: {
    oneLiner: {
      fr: "Toutes les sorties enfants dans une seule appli, sans le casse-tête.",
      en: "Every kids' outing in one app, without the headache.",
    },
    whatItIs: {
      fr: "App mobile (iOS + Android) qui rassemble toutes les activités pour enfants au même endroit : plus de 6 000 sorties gratuites et payantes partout en France, de plus de 100 types. Les parents créent un profil famille pour des recommandations personnalisées.",
      en: "A mobile app (iOS + Android) that gathers every kids' activity in one place: 6,000+ free and paid outings across France, in over 100 categories. Parents create a family profile for personalized recommendations.",
    },
    keyFeatures: [
      {
        fr: "Annuaire de 6 000+ sorties enfants, gratuites et payantes, 100+ types d'activités",
        en: "Directory of 6,000+ kids' outings, free and paid, 100+ activity types",
      },
      {
        fr: "Profil famille (nombre d'enfants, âges, préférences) pour des recos sur mesure",
        en: "Family profile (number of kids, ages, preferences) for tailored recommendations",
      },
      {
        fr: "Recherche intelligente filtrable par lieu, horaire et critères précis",
        en: "Smart search filterable by location, time and precise criteria",
      },
      {
        fr: "Bouton magique (à venir) qui choisit la sortie idéale selon le profil et les favoris",
        en: "Magic button (coming) that picks the ideal outing from your profile and favourites",
      },
    ],
    targetUser: {
      fr: "Parents et familles cherchant des activités pour leurs enfants",
      en: "Parents and families looking for activities for their kids",
    },
    notable: {
      fr: "Base de plus de 6 000 activités couvrant toute la France, gratuites comme payantes.",
      en: "A base of 6,000+ activities covering all of France, both free and paid.",
    },
  },
  karibteck: {
    oneLiner: {
      fr: "Agence web caribéenne : sites, apps mobiles et agents IA sur-mesure pour les entreprises des Antilles.",
      en: "Caribbean web agency: custom sites, mobile apps and AI agents for West Indies businesses.",
    },
    whatItIs: {
      fr: "Agence digitale des Antilles françaises qui combine expertise locale et standards de développement internationaux. Sites web, applications mobiles et solutions IA 100 % sur-mesure, sans templates, avec une vraie compréhension des réalités fiscales et logistiques des DOM.",
      en: "A French West Indies digital agency combining local expertise with international development standards. Custom-built websites, mobile apps and AI solutions — no templates — with a real grasp of the tax and logistics realities of the overseas territories.",
    },
    keyFeatures: [
      {
        fr: "Sites web rapides, optimisés SEO et pensés pour la conversion",
        en: "Fast, SEO-optimized websites built for conversion",
      },
      {
        fr: "Applications mobiles iOS et Android (commandes, réservations, fidélité)",
        en: "iOS and Android mobile apps (orders, bookings, loyalty)",
      },
      {
        fr: "Agents IA qui automatisent les process et répondent aux clients 24/7",
        en: "AI agents that automate processes and answer customers 24/7",
      },
      {
        fr: "100 % sur-mesure, accompagnement et maintenance post-lancement",
        en: "Fully custom work, support and maintenance after launch",
      },
    ],
    targetUser: {
      fr: "Entreprises, entrepreneurs et marques des Antilles françaises (Guadeloupe, Martinique)",
      en: "Businesses, founders and brands in the French West Indies (Guadeloupe, Martinique)",
    },
    notable: {
      fr: "Positionnement hybride : expertise locale caribéenne + standards de dev internationaux, avec compréhension des contraintes DOM.",
      en: "A hybrid positioning: Caribbean local expertise + international dev standards, with a real understanding of overseas-territory constraints.",
    },
  },
};
